version: '3'
services:
 postgres:
  image: postgres:13.3
  environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
  ports:
    - "5432:5432"
volumes:
  postgres: